import { readFileSync } from "node:fs";
import { fs } from "./src/fs/index.js";
import { bgSubmit, bgPeek } from "./src/bgworker.js";
const scriptText = readFileSync("www/examples/textures/texture-dirt.sh", "utf8");
const t0 = Date.now();
const { id, promise } = await bgSubmit(scriptText, ["--tsv", "--size", "32", "--seed", "20240812"]);
console.log("bgSubmit returned:", Date.now() - t0, "ms, id", id);
await promise;
const j = bgPeek(id);
console.log("done:", j.done, "bytes:", j.out.length, "starts:", j.out.startsWith("#texture"));
