// GLSL ES 1.00 (WebGL1) — generated by the sh→GLSL backend
precision highp float;
precision highp int;

attribute vec3 aPosition;
attribute vec3 aShade;
attribute vec2 aUv;
uniform vec3 uCamPos;
uniform float uCamYaw;
uniform float uCamShift;
uniform vec3 uObjPos;
uniform vec3 uScale;
uniform vec3 uBlockColor;
uniform float uOverlay;
varying highp vec4 vColor;
varying highp vec2 vUv;

void main() {
    int g_ap_x;
    int g_ap_y;
    int g_ap_z;
    int g_ash_b;
    int g_ash_g;
    int g_ash_r;
    int g_auv_u;
    int g_auv_v;
    float g_c;
    float g_cx;
    float g_cy;
    float g_cz;
    float g_dx;
    float g_dy;
    float g_dz;
    float g_rad;
    float g_relx;
    float g_rely;
    float g_relz;
    float g_s;
    int g_ublk_b;
    int g_ublk_g;
    int g_ublk_r;
    int g_ucp_x;
    int g_ucp_y;
    int g_ucp_z;
    int g_ucs;
    int g_ucy_m;
    int g_uop_x;
    int g_uop_y;
    int g_uop_z;
    int g_uov;
    int g_usc_x;
    int g_usc_y;
    int g_usc_z;
    int g_vc_a;
    int g_vc_b;
    int g_vc_g;
    int g_vc_r;
    float g_vp_w;
    float g_vp_x;
    float g_vp_y;
    float g_vp_z;
    int g_vu_u;
    int g_vu_v;
    float g_w;
    float g_wx;
    float g_wy;
    float g_wz;

    g_ap_x = int(aPosition.x * 1000.0);
    g_ap_y = int(aPosition.y * 1000.0);
    g_ap_z = int(aPosition.z * 1000.0);
    g_ash_r = int(aShade.r * 1000.0);
    g_ash_g = int(aShade.g * 1000.0);
    g_ash_b = int(aShade.b * 1000.0);
    g_auv_u = int(aUv.x * 1000.0);
    g_auv_v = int(aUv.y * 1000.0);
    g_ucp_x = int(uCamPos.x * 1000.0);
    g_ucp_y = int(uCamPos.y * 1000.0);
    g_ucp_z = int(uCamPos.z * 1000.0);
    g_ucy_m = int(uCamYaw * 1000.0);
    g_ucs = int(uCamShift * 1000.0);
    g_uop_x = int(uObjPos.x * 1000.0);
    g_uop_y = int(uObjPos.y * 1000.0);
    g_uop_z = int(uObjPos.z * 1000.0);
    g_usc_x = int(uScale.x * 1000.0);
    g_usc_y = int(uScale.y * 1000.0);
    g_usc_z = int(uScale.z * 1000.0);
    g_ublk_r = int(uBlockColor.r * 1000.0);
    g_ublk_g = int(uBlockColor.g * 1000.0);
    g_ublk_b = int(uBlockColor.b * 1000.0);
    g_uov = int(uOverlay * 1000.0);
    g_wx = ((((((float(g_ap_x)) * (float(g_usc_x)))) / (1000000.0))) + (((float(g_uop_x)) / (1000.0))));
    g_wy = ((((((float(g_ap_y)) * (float(g_usc_y)))) / (1000000.0))) + (((float(g_uop_y)) / (1000.0))));
    g_wz = ((((((float(g_ap_z)) * (float(g_usc_z)))) / (1000000.0))) + (((float(g_uop_z)) / (1000.0))));
    g_vc_r = (((g_ash_r * g_ublk_r)) / 1000);
    g_vc_g = (((g_ash_g * g_ublk_g)) / 1000);
    g_vc_b = (((g_ash_b * g_ublk_b)) / 1000);
    g_vc_a = 1000;
    if ((g_uov > 500)) {
        g_vp_x = (((g_wx + (((float(g_ucs)) / (1000.0))))) + (0.0));
        g_vp_y = g_wy;
        g_vp_z = ((((float(g_uov)) * (0.0))) - (0.95));
        g_vp_w = ((((float(g_uov)) * (0.0))) + (1.0));
        g_vu_u = 0;
        g_vu_v = 0;
    } else {
        g_cx = ((((float(g_ucp_x)) / (1000.0))) + (0.0));
        g_cy = ((((float(g_ucp_y)) / (1000.0))) + (0.5));
        g_cz = ((((float(g_ucp_z)) / (1000.0))) + (0.0));
        g_dx = (((g_wx - g_cx)) + (0.0));
        g_dy = (((g_wy - g_cy)) + (0.0));
        g_dz = (((g_wz - g_cz)) + (0.0));
        g_rad = ((((float(g_ucy_m)) * (3.14159265))) / (180000.0));
        g_c = ((cos(g_rad)) + (0.0));
        g_s = ((sin(g_rad)) + (0.0));
        g_relx = (((((g_dx * g_c)) + ((g_dz * g_s)))) + (0.0));
        g_rely = g_dy;
        g_relz = ((((((0.0) - ((g_dx * g_s)))) + ((g_dz * g_c)))) + (0.0));
        g_w = ((((0.0) - g_relz)) + (0.0));
        g_vp_x = (((((g_relx * (0.7))) + (((((float(g_ucs)) * g_w)) / (1000.0))))) + (0.0));
        g_vp_y = (g_rely * (0.45));
        g_vp_z = (((g_w * g_w)) / (64.0));
        g_vp_w = g_w;
        if ((g_usc_x > 1100)) {
            g_vu_u = (((((g_ap_x * g_usc_x)) / 1000)) + g_uop_x);
            g_vu_v = (((((g_ap_z * g_usc_z)) / 1000)) + g_uop_z);
        } else {
            g_vu_u = g_auv_u;
            g_vu_v = g_auv_v;
        }
    }
    gl_Position = vec4(g_vp_x, g_vp_y, g_vp_z, g_vp_w);
    vColor = vec4(float(g_vc_r) / 1000.0, float(g_vc_g) / 1000.0, float(g_vc_b) / 1000.0, float(g_vc_a) / 1000.0);
    vUv = vec2(float(g_vu_u) / 1000.0, float(g_vu_v) / 1000.0);
}
// TODO(unsupported): 0 construct(s) — see shir_to_glsl limitations
