// GLSL ES 1.00 (WebGL1) — generated by the sh→GLSL backend
precision mediump float;
precision mediump int;

varying highp vec4 vColor;
varying highp vec2 vUv;
uniform sampler2D uTex;
uniform sampler2D uCrack;
uniform int uDamage;

void main() {
    int g_frag_x;
    int g_frag_y;
    float g_fr;
    float g_fg;
    float g_fb;
    float g_r;
    float g_g;
    float g_b;
    int g_scan;
    float g_mix;
    int g_hash;
    int g_corrupt;
    int g_vx;
    int g_vy;
    int g_edge;
    int g_dim;

    g_frag_x = int(gl_FragCoord.x);
    g_frag_y = int(gl_FragCoord.y);
    // the 0..127 / 0..255 quantize boundaries are preserved — same
    // colour scale and effect placement as the fixed-point pipeline
    g_fr = float(int(vColor.r * 127.0));
    g_fg = float(int(vColor.g * 127.0));
    g_fb = float(int(vColor.b * 127.0));
    vec4 _tex = texture2D(uTex, fract(vUv));
    g_r = (g_fr * float(int(_tex.r * 255.0))) / 128.0;
    g_g = (g_fg * float(int(_tex.g * 255.0))) / 128.0;
    g_b = (g_fb * float(int(_tex.b * 255.0))) / 128.0;
    g_scan = int(mod(float(g_frag_y), 6.0));
    if ((g_scan == 0)) {
        g_r = (g_r * 0.9);
        g_g = (g_g * 0.9);
        g_b = (g_b * 0.9);
    }
    if ((uDamage > 0)) {
        vec4 _crack = texture2D(uCrack, fract(vUv));
        g_mix = min((float(uDamage) * float(int(_crack.a * 127.0))), 127.0);
        g_r = (g_r - (((g_r - float(int(_crack.r * 127.0)))) * (g_mix / 128.0)));
        g_g = (g_g - (((g_g - float(int(_crack.g * 127.0)))) * (g_mix / 128.0)));
        g_b = (g_b - (((g_b - float(int(_crack.b * 127.0)))) * (g_mix / 128.0)));
    }
    g_hash = (((g_frag_x * 7)) + ((g_frag_y * 13)));
    g_corrupt = int(mod(float(g_hash), 97.0));
    if ((g_corrupt == 0)) {
        g_r = 255.0;
        g_g = (g_g * 0.5);
        g_b = (g_b * 0.5);
    }
    g_vx = (g_frag_x - 400);
    g_vy = (g_frag_y - 300);
    if ((g_vx < 0)) {
        g_vx = (0 - g_vx);
    }
    if ((g_vy < 0)) {
        g_vy = (0 - g_vy);
    }
    g_edge = (g_vx + g_vy);
    if ((g_edge > 450)) {
        g_dim = (g_edge - 450);
        if ((g_dim > 30)) {
            g_dim = 30;
        }
        g_r = (g_r - ((g_r * float(g_dim)) / 256.0));
        g_g = (g_g - ((g_g * float(g_dim)) / 256.0));
        g_b = (g_b - ((g_b * float(g_dim)) / 256.0));
    }
    gl_FragColor = vec4((max(g_r, 0.0)) / 255.0, (max(g_g, 0.0)) / 255.0, (max(g_b, 0.0)) / 255.0, 1.0);
}
// TODO(unsupported): 0 construct(s) — see shir_to_glsl limitations
