// GLSL ES 1.00 (WebGL1) — generated by the sh→GLSL backend
precision mediump float;
precision mediump int;

int out_buf[4];
varying highp vec4 vColor;
varying highp vec2 vUv;
uniform sampler2D uTex;
uniform sampler2D uCrack;
uniform int uDamage;

void main() {
    int g_b;
    int g_corrupt;
    int g_cr_a;
    int g_cr_b;
    int g_cr_g;
    int g_cr_r;
    int g_damage;
    int g_dim;
    int g_edge;
    int g_frag_x;
    int g_frag_y;
    int g_fx;
    int g_fy;
    int g_g;
    int g_hash;
    int g_mix;
    int g_r;
    int g_scan;
    int g_tex_b;
    int g_tex_g;
    int g_tex_r;
    int g_uv_x;
    int g_uv_y;
    int g_vcolor_b;
    int g_vcolor_g;
    int g_vcolor_r;
    int g_vx;
    int g_vy;

    g_frag_x = int(gl_FragCoord.x);
    g_frag_y = int(gl_FragCoord.y);
    g_vcolor_r = int(vColor.r * 127.0);
    g_vcolor_g = int(vColor.g * 127.0);
    g_vcolor_b = int(vColor.b * 127.0);
    vec4 _tex = texture2D(uTex, fract(vUv));
    g_tex_r = int(_tex.r * 255.0);
    g_tex_g = int(_tex.g * 255.0);
    g_tex_b = int(_tex.b * 255.0);
    g_damage = uDamage;
    g_fx = g_frag_x;
    g_fy = g_frag_y;
    g_r = g_vcolor_r;
    g_g = g_vcolor_g;
    g_b = g_vcolor_b;
    g_r = (((g_r * g_tex_r)) / 128);
    g_g = (((g_g * g_tex_g)) / 128);
    g_b = (((g_b * g_tex_b)) / 128);
    g_scan = (g_fy - (6 * (g_fy / 6)));
    if ((g_scan == 0)) {
        g_r = (((g_r * 90)) / 100);
        g_g = (((g_g * 90)) / 100);
        g_b = (((g_b * 90)) / 100);
    }
    if ((g_damage > 0)) {
        vec4 _crack = texture2D(uCrack, fract(vUv));
        g_cr_r = int(_crack.r * 127.0);
        g_cr_g = int(_crack.g * 127.0);
        g_cr_b = int(_crack.b * 127.0);
        g_cr_a = int(_crack.a * 127.0);
        g_mix = (((g_damage * g_cr_a)) / 2);
        if ((g_mix > 127)) {
            g_mix = 127;
        }
        g_r = (g_r - ((((((g_r - g_cr_r)) * g_mix)) / 128)));
        g_g = (g_g - ((((((g_g - g_cr_g)) * g_mix)) / 128)));
        g_b = (g_b - ((((((g_b - g_cr_b)) * g_mix)) / 128)));
    }
    g_hash = (((g_fx * 7)) + ((g_fy * 13)));
    g_corrupt = (g_hash - (97 * (g_hash / 97)));
    if ((g_corrupt == 0)) {
        g_r = 255;
        g_g = (g_g / 2);
        g_b = (g_b / 2);
    }
    g_vx = (g_fx - 400);
    g_vy = (g_fy - 300);
    if ((g_vx < 0)) {
        g_vx = (0 - g_vx);
    }
    if ((g_vy < 0)) {
        g_vy = (0 - g_vy);
    }
    g_edge = (g_vx + g_vy);
    if ((g_edge > 450)) {
        g_dim = (g_edge - 450);
        if ((g_dim > 30)) {
            g_dim = 30;
        }
        g_r = (g_r - ((((g_r * g_dim)) / 256)));
        g_g = (g_g - ((((g_g * g_dim)) / 256)));
        g_b = (g_b - ((((g_b * g_dim)) / 256)));
    }
    if ((g_r < 0)) {
        g_r = 0;
    }
    if ((g_g < 0)) {
        g_g = 0;
    }
    if ((g_b < 0)) {
        g_b = 0;
    }
    out_buf[0] = g_r;
    out_buf[1] = g_g;
    out_buf[2] = g_b;
    out_buf[3] = 255;
    gl_FragColor = vec4(float(out_buf[0]) / 255.0, float(out_buf[1]) / 255.0, float(out_buf[2]) / 255.0, float(out_buf[3]) / 255.0);
}
// TODO(unsupported): 0 construct(s) — see shir_to_glsl limitations
