// GLSL ES 1.00 (WebGL1) — generated by the sh→GLSL backend
precision mediump float;
precision mediump int;

int out_buf[4];
varying vec4 vColor;

void main() {
    int g_b;
    int g_corrupt;
    int g_dim;
    int g_edge;
    int g_frag_x;
    int g_frag_y;
    int g_fx;
    int g_fy;
    int g_g;
    int g_hash;
    int g_r;
    int g_scan;
    int g_vcolor_b;
    int g_vcolor_g;
    int g_vcolor_r;
    int g_vx;
    int g_vy;

    g_frag_x = int(gl_FragCoord.x);
    g_frag_y = int(gl_FragCoord.y);
    g_vcolor_r = int(vColor.r * 255.0);
    g_vcolor_g = int(vColor.g * 255.0);
    g_vcolor_b = int(vColor.b * 255.0);
    g_fx = g_frag_x;
    g_fy = g_frag_y;
    g_r = g_vcolor_r;
    g_g = g_vcolor_g;
    g_b = g_vcolor_b;
    g_scan = (g_fy - (6 * (g_fy / 6)));
    if ((g_scan == 0)) {
        g_r = (((g_r * 90)) / 100);
        g_g = (((g_g * 90)) / 100);
        g_b = (((g_b * 90)) / 100);
    }
    g_hash = (((g_fx * 7)) + ((g_fy * 13)));
    g_corrupt = (g_hash - (97 * (g_hash / 97)));
    if ((g_corrupt == 0)) {
        g_r = 255;
        g_g = (g_g / 2);
        g_b = (g_b / 2);
    }
    g_vx = (g_fx - 120);
    g_vy = (g_fy - 90);
    if ((g_vx < 0)) {
        g_vx = (0 - g_vx);
    }
    if ((g_vy < 0)) {
        g_vy = (0 - g_vy);
    }
    g_edge = (g_vx + g_vy);
    if ((g_edge > 150)) {
        g_dim = (g_edge - 150);
        if ((g_dim > 40)) {
            g_dim = 40;
        }
        g_r = (g_r - g_dim);
        g_g = (g_g - g_dim);
        g_b = (g_b - g_dim);
    }
    if ((g_r < 0)) {
        g_r = 0;
    }
    if ((g_g < 0)) {
        g_g = 0;
    }
    if ((g_b < 0)) {
        g_b = 0;
    }
    out_buf[0] = g_r;
    out_buf[1] = g_g;
    out_buf[2] = g_b;
    out_buf[3] = 255;
    gl_FragColor = vec4(float(out_buf[0]) / 255.0, float(out_buf[1]) / 255.0, float(out_buf[2]) / 255.0, float(out_buf[3]) / 255.0);
}
// TODO(unsupported): 0 construct(s) — see shir_to_glsl limitations
