// ─── bash2js: bash → JavaScript, transpiled in the browser ─────
//
// The full bash → JS pipeline runs entirely in the browser:
//
//   bash ──debashcl.wasm──▶ ESTree ──estree.js──▶ JavaScript
//
// debashcl.wasm is gmatht/sh2perl's debashc CLI compiled as a WASI
// reactor — the ONE compiler binary (no separate debashc / debashl /
// sh2perl binaries). It parses bash and emits ESTree JSON; src/estree.js
// lowers that to JavaScript against the sh2.* runtime (src/sh2runtime.js)
// and the shell's `env` object. The sh2perl / sh2js / otranspiler
// commands are the user-facing wrappers over the same reactor
// (src/sh2lib.js); otranspiler is the unified interface (debashc's
// successor).
//
// Usage in jtsh:
//   bash2js 'echo hello world'     → prints the generated JS
//   bash2js -f script.sh           → transpile a file from the VFS
//   cat script.sh | bash2js        → transpile from a pipe
// -----------------------------------------------------------------

import { env } from "./env.js";
import { getSh2Lib } from "./sh2lib.js";
import { getOtranspilerl } from "./otranspilerl.js";
import { estreeToJs, keepVariables } from "./estree.js";
import { a1LiteralValue } from "./shellcore/transpile.js";

// ── the game's bash engine: otranspilerl vs the legacy debashcl ──
// `.sh` files (runBashScript → runBash → bashToJS) can run on EITHER
// wasm:
//   • debashcl.wasm — the parse-tree path (current default; works, but
//     predates the landed perf transforms and needs a rebuild that the
//     EPOCHREALTIME regression blocks — estree-…-233001).
//   • otranspilerl.wasm — the unified A1 path with ALL the landed
//     transforms (native tests, inlining, typed lowering, DCE, …); the
//     redirect bridge + view parameterization are already in. The game
//     cannot switch yet because the A1 path hangs in the radar-base
//     scan (estree-…-235901 — a typed-lifting loop desync).
// FLIP THIS to route `.sh` execution through otranspilerl.wasm once
// the worker lands 235901 (and keep debashcl as the throw-fallback).
export const USE_OTRANSPILERL_BASH = false;

function escapeJsComment(text) {
  return text.split("\n").map((l) => "//   " + l).join("\n");
}

// ─── bashToJSA1: the otranspilerl (A1) path ────────────────────
// bash → A1 shIR → ESTree → JS via the unified wasm. Mirrors
// runShellScript's array handling: the A1 path drops bare `arr=(…)`
// assignments whose reads are bare, so the literal arrays are
// pre-seeded (returned as arrayVals for the runtime) and keepVariables
// emits the STORE SYNC. Returns { js, ast, arrayVals }.
async function bashToJSA1(fs, bashSource) {
  const lib = await getOtranspilerl();
  const program = JSON.parse(lib.transpile(String(bashSource), "sh", "js"));
  const scriptArrays = [];
  const arrayVals = new Map();
  const a1 = JSON.parse(lib.shir(String(bashSource)));
  for (const st of a1.stmts || []) {
    if (st && st.type === "Assign" && st.targets && st.targets[0]) {
      const t = st.targets[0];
      if (t.var && !(t.indices && t.indices.length)) {
        const val = a1LiteralValue(st.expr);
        if (Array.isArray(val)) { scriptArrays.push(t.var); arrayVals.set(t.var, val); }
      }
    }
  }
  keepVariables(program, scriptArrays);
  const js =
    "// ── Generated by bash2js (otranspilerl A1 path) ──────────────\n" +
    "// bash → A1 → ESTree → JS against the sh2.* runtime — the unified\n" +
    "// wasm with the landed perf transforms (native tests, inlining, …)\n" +
    "// bash source:\n" +
    escapeJsComment(bashSource) + "\n" +
    "// ── transpiled statements ─────────────────────────────\n" +
    await estreeToJs(program);
  return { js, ast: program, arrayVals };
}

// ─── bashToJS: the one-call entry point ─────────────────────────
// Returns { js, ast, arrayVals? }: the generated JavaScript (header +
// transpiled statements) and the ESTree AST. Default pipeline: bash →
// ESTree (debashcl.wasm, the unified debashc CLI reactor) → JS
// (estree.js), run against the sh2.* runtime. When
// USE_OTRANSPILERL_BASH is on, the A1 path is preferred with a
// throw-fallback to debashcl.
export async function bashToJS(fs, bashSource) {
  if (USE_OTRANSPILERL_BASH) {
    try {
      return await bashToJSA1(fs, bashSource);
    } catch (e) {
      console.warn("bash2js: otranspilerl A1 path failed (" + e.message + ") — falling back to debashcl");
    }
  }
  const lib = await getSh2Lib();
  const ast = await lib.toEstree(bashSource);
  const js =
    "// ── Generated by bash2js (debashcl ESTree path) ──────────────\n" +
    "// bash → ESTree → JS against the sh2.* runtime — full bash support\n" +
    "// bash source:\n" +
    escapeJsComment(bashSource) + "\n" +
    "// ── transpiled statements ─────────────────────────────\n" +
    await estreeToJs(ast);
  return { js, ast };
}

// ─── sh2lib facade: handed to .js commands as the `sh2lib` param ─
// Lets /bin/sh2js.js, /bin/sh2perl.js, /bin/otranspiler.js (and any user
// command) drive the debashc reactor directly, in both shells — and, via
// the unified otranspilerl library (the real debashl core + all nine
// backend renderers), the full sh → A1 → target pipeline.
export function buildSh2LibFacade(fs) {
  return {
    toEstree: (src) => getSh2Lib().then((l) => l.toEstree(src)),
    toPerl: (src) => getSh2Lib().then((l) => l.toPerl(src)),
    lex: (src) => getSh2Lib().then((l) => l.lex(src)),
    version: () => getSh2Lib().then((l) => l.version()),
    bashToJs: async (src) => (await bashToJS(fs, src)).js,
    // Windows batch → JS: the bat2js pipeline (busybox's bat-sh-go
    // frontend → A1 shIR → otranspilerl estree → JS against sh2.*).
    batToJs: async (src) => (await import("./bat2js.js")).batToJS(fs, src).then((r) => r.js),
    // the unified otranspilerl library (src/otranspilerl.js):
    //   shir(src) → A1 shIR JSON       (the debashl core, full bash)
    //   transpile(src, s, t) → target  (sh/shir sources, in-process)
    //   render(a1, t) → target         (A1 → any of the nine backends)
    //   estreeToJs(estree) → JS source (the shell's own emitter)
    shir: async (src) => (await getOtranspilerl()).shir(String(src)),
    transpile: async (src, s, t) => (await getOtranspilerl()).transpile(String(src), s, t),
    render: async (a1, t) => (await getOtranspilerl()).render(String(a1), t),
    glsl: async (src) => (await getOtranspilerl()).glsl(String(src)),   // shell → GLSL ES 1.00 (the sh2glsl path)
    estreeToJs: async (estree) => estreeToJs(estree),
    // the unified frontend (src/busybox.js) — the SAME artifact the
    // otranspiler GUI uses: the shipped prebuilt
    // www/wasm-bin/otranspiler-busybox.wasm, staged into the VFS and
    // run by GoRunner (built with the in-browser Go toolchain only if
    // the prebuilt is ever missing). busyboxA1(src, lang) → A1 shIR
    // JSON for go/py/c/pl/zsh/fish sources.
    busyboxA1: async (src, lang) => {
      const { ensureBusyboxWasm, busyboxA1 } = await import("./busybox.js");
      const { GoRunner } = await import("./go.js");
      const goRunner = new GoRunner(fs, { baseUrl: "www/" });  // www/ in node CLI (page-relative in the browser)
      const fetchBytes = async () => {
        if (typeof process !== "undefined" && process.versions && process.versions.node) {
          const { readFile } = await import("node:fs/promises");
          return new Uint8Array(await readFile(process.cwd() + "/www/wasm-bin/otranspiler-busybox.wasm"));
        }
        const { BUSYBOX_VERSION } = await import("./busybox.js");
        const resp = await fetch("wasm-bin/otranspiler-busybox.wasm?v=" + BUSYBOX_VERSION);
        if (!resp.ok) throw new Error("prebuilt busybox fetch " + resp.status);
        return new Uint8Array(await resp.arrayBuffer());
      };
      const wasmPath = await ensureBusyboxWasm(fs, {
        goRunner, fetchBytes, onLog: (m) => console.log(m),
      });
      return busyboxA1(String(src), lang, { fs, wasmPath, goRunner });
    },
  };
}

// ─── runBash: transpile AND execute in one call ────────────────
// The "type bash, get generated JS executed" entry point: transpiles
// the source with bashToJS and runs the generated JS in a shell
// context where `fs`, `env`, `stdout`, `stderr` and `__runCmd` (the
// shell's own command runner — used for pipelines, redirection and
// command substitution) are in scope. Returns the script's exit code.
//
// The generated JS runs with the `sh2.*` runtime (createSh2Runtime)
// in scope. `scriptArgs` become $1..$9/$@/$#.
export async function runBash(fs, source, { stdout, stderr, runCmd, args = [], argv0 = "bash", markers = [], stdin } = {}) {
  let { js, arrayVals } = await bashToJS(fs, source);
  // Marker echos (the REPL's `echo '<marker>'` line brackets) are
  // rewritten to direct stdout writes. Running them through exec would
  // set $? to 0 right before the user's line runs — breaking
  // `false` followed by `echo $?` (real bash reports 1). A direct
  // write bypasses exec entirely, so the exit status carries across
  // the boundary exactly like in bash.
  for (const m of markers) {
    if (!m) continue;
    const echoCall = `sh2.exec("echo", [${JSON.stringify(m)}])`;
    if (js.includes(echoCall)) {
      js = js.replace(echoCall, `stdout.write(${JSON.stringify(m + "\n")})`);
    }
  }
  const out = stdout || { write: () => {} };
  const err = stderr || { write: (s) => out.write(s) };
  const { createSh2Runtime } = await import("./sh2runtime.js");
  const rt = createSh2Runtime({ fs, env, shellExec: runCmd, stdout: out, stderr: err, args, argv0 });
  // the otranspilerl A1 path pre-seeds the literal arrays (the A1
  // renderer drops bare `arr=(…)` reads); the debashcl path emits
  // setArray itself.
  if (arrayVals) { for (const [name, vals] of arrayVals) { try { rt.sh2.setArray(name, vals); } catch {} } }
  // pipe input → the transpiled code's read_line/getline bridge (the c
  // frontend's sh2.stdin cursor)
  if (stdin !== undefined) { try { rt.sh2.stdin = stdin; } catch {} }
  const fn = new Function("args", "fs", "env", "stdout", "stderr", "__runCmd", "sh2", `
    return (async () => {
      ${js}
    })();
  `);
  const code = await fn([], fs, env, out, err, runCmd, rt.sh2);
  return typeof code === "number" ? code : 0;
}
