// ─── bash2js: bash → JavaScript, transpiled in the browser ─────
//
// The full bash → JS pipeline runs entirely in the browser:
//
//   bash ──debashcl.wasm──▶ ESTree ──estree.js──▶ JavaScript
//
// debashcl.wasm is gmatht/sh2perl's debashc CLI compiled as a WASI
// reactor — the ONE compiler binary (no separate debashc / debashl /
// sh2perl binaries). It parses bash and emits ESTree JSON; src/estree.js
// lowers that to JavaScript against the sh2.* runtime (src/sh2runtime.js)
// and the shell's `env` object. The sh2perl / sh2js / otranspiler
// commands are the user-facing wrappers over the same reactor
// (src/sh2lib.js); otranspiler is the unified interface (debashc's
// successor).
//
// Usage in jtsh:
//   bash2js 'echo hello world'     → prints the generated JS
//   bash2js -f script.sh           → transpile a file from the VFS
//   cat script.sh | bash2js        → transpile from a pipe
// -----------------------------------------------------------------

import { env } from "./env.js";
import { getSh2Lib } from "./sh2lib.js";
import { getOtranspilerl } from "./otranspilerl.js";
import { estreeToJs } from "./estree.js";

function escapeJsComment(text) {
  return text.split("\n").map((l) => "//   " + l).join("\n");
}

// ─── bashToJS: the one-call entry point ─────────────────────────
// Returns { js, ast }: the generated JavaScript (header + transpiled
// statements) and the ESTree AST. Pipeline: bash → ESTree
// (debashcl.wasm, the unified debashc CLI reactor) → JS (estree.js),
// run against the sh2.* runtime (src/sh2runtime.js).
export async function bashToJS(fs, bashSource) {
  const lib = await getSh2Lib();
  const ast = await lib.toEstree(bashSource);
  const js =
    "// ── Generated by bash2js (debashcl ESTree path) ──────────────\n" +
    "// bash → ESTree → JS against the sh2.* runtime — full bash support\n" +
    "// bash source:\n" +
    escapeJsComment(bashSource) + "\n" +
    "// ── transpiled statements ─────────────────────────────\n" +
    await estreeToJs(ast);
  return { js, ast };
}

// ─── sh2lib facade: handed to .js commands as the `sh2lib` param ─
// Lets /bin/sh2js.js, /bin/sh2perl.js, /bin/otranspiler.js (and any user
// command) drive the debashc reactor directly, in both shells — and, via
// the unified otranspilerl library (the real debashl core + all nine
// backend renderers), the full sh → A1 → target pipeline.
export function buildSh2LibFacade(fs) {
  return {
    toEstree: (src) => getSh2Lib().then((l) => l.toEstree(src)),
    toPerl: (src) => getSh2Lib().then((l) => l.toPerl(src)),
    lex: (src) => getSh2Lib().then((l) => l.lex(src)),
    version: () => getSh2Lib().then((l) => l.version()),
    bashToJs: async (src) => (await bashToJS(fs, src)).js,
    // the unified otranspilerl library (src/otranspilerl.js):
    //   shir(src) → A1 shIR JSON       (the debashl core, full bash)
    //   transpile(src, s, t) → target  (sh/shir sources, in-process)
    //   render(a1, t) → target         (A1 → any of the nine backends)
    //   estreeToJs(estree) → JS source (the shell's own emitter)
    shir: async (src) => (await getOtranspilerl()).shir(String(src)),
    transpile: async (src, s, t) => (await getOtranspilerl()).transpile(String(src), s, t),
    render: async (a1, t) => (await getOtranspilerl()).render(String(a1), t),
    estreeToJs: async (estree) => estreeToJs(estree),
  };
}

// ─── runBash: transpile AND execute in one call ────────────────
// The "type bash, get generated JS executed" entry point: transpiles
// the source with bashToJS and runs the generated JS in a shell
// context where `fs`, `env`, `stdout`, `stderr` and `__runCmd` (the
// shell's own command runner — used for pipelines, redirection and
// command substitution) are in scope. Returns the script's exit code.
//
// The generated JS runs with the `sh2.*` runtime (createSh2Runtime)
// in scope. `scriptArgs` become $1..$9/$@/$#.
export async function runBash(fs, source, { stdout, stderr, runCmd, args = [], argv0 = "bash", markers = [] } = {}) {
  let { js } = await bashToJS(fs, source);
  // Marker echos (the REPL's `echo '<marker>'` line brackets) are
  // rewritten to direct stdout writes. Running them through exec would
  // set $? to 0 right before the user's line runs — breaking
  // `false` followed by `echo $?` (real bash reports 1). A direct
  // write bypasses exec entirely, so the exit status carries across
  // the boundary exactly like in bash.
  for (const m of markers) {
    if (!m) continue;
    const echoCall = `sh2.exec("echo", [${JSON.stringify(m)}])`;
    if (js.includes(echoCall)) {
      js = js.replace(echoCall, `stdout.write(${JSON.stringify(m + "\n")})`);
    }
  }
  const out = stdout || { write: () => {} };
  const err = stderr || { write: (s) => out.write(s) };
  const { createSh2Runtime } = await import("./sh2runtime.js");
  const rt = createSh2Runtime({ fs, env, shellExec: runCmd, stdout: out, stderr: err, args, argv0 });
  const fn = new Function("args", "fs", "env", "stdout", "stderr", "__runCmd", "sh2", `
    return (async () => {
      ${js}
    })();
  `);
  const code = await fn([], fs, env, out, err, runCmd, rt.sh2);
  return typeof code === "number" ? code : 0;
}
