// ─── bash2js: bash → JavaScript, transpiled in the browser ─────
//
// The full bash → JS pipeline runs entirely in the browser:
//
//   bash ──debashcl.wasm──▶ ESTree ──estree.js──▶ JavaScript
//
// debashcl.wasm is gmatht/sh2perl's debashc CLI compiled as a WASI
// reactor — the ONE compiler binary (no separate debashc / debashl /
// sh2perl binaries). It parses bash and emits ESTree JSON; src/estree.js
// lowers that to JavaScript against the sh2.* runtime (src/sh2runtime.js)
// and the shell's `env` object. The sh2perl / sh2js / otranspiler
// commands are the user-facing wrappers over the same reactor
// (src/sh2lib.js); otranspiler is the unified interface (debashc's
// successor).
//
// Usage in jtsh:
//   bash2js 'echo hello world'     → prints the generated JS
//   bash2js -f script.sh           → transpile a file from the VFS
//   cat script.sh | bash2js        → transpile from a pipe
// -----------------------------------------------------------------

import { env } from "./env.js";
import { getSh2Lib } from "./sh2lib.js";
import { getOtranspilerl } from "./otranspilerl.js";
import { estreeToJs, keepVariables } from "./estree.js";

// ── the game's bash engine: otranspilerl vs the legacy debashcl ──
// `.sh` files (runBashScript → runBash → bashToJS) can run on EITHER
// wasm:
//   • debashcl.wasm — the parse-tree path (current default; works, but
//     predates the landed perf transforms and needs a rebuild that the
//     EPOCHREALTIME regression blocks — estree-…-233001).
//   • otranspilerl.wasm — the unified A1 path with ALL the landed
//     transforms (native tests, inlining, typed lowering, DCE, …); the
//     redirect bridge + view parameterization are already in. The game
//     cannot switch yet because the A1 path hangs in the radar-base
//     scan (estree-…-235901 — a typed-lifting loop desync).
// FLIP THIS to route `.sh` execution through otranspilerl.wasm once
// the worker lands 235901 (and keep debashcl as the throw-fallback).
export const USE_OTRANSPILERL_BASH = true;

function escapeJsComment(text) {
  return text.split("\n").map((l) => "//   " + l).join("\n");
}

// ─── bashToJSA1: the otranspilerl (A1) path ────────────────────
// bash → A1 shIR → ESTree → JS via the unified wasm. Mirrors
// runShellScript's array handling: the A1 path drops bare `arr=(…)`
// assignments whose reads are bare, so the literal arrays are
// pre-seeded (returned as arrayVals for the runtime) and keepVariables
// emits the STORE SYNC. Returns { js, ast, arrayVals }.
async function bashToJSA1(fs, bashSource) {
  const lib = await getOtranspilerl();
  const program = JSON.parse(lib.transpile(String(bashSource), "sh", "js"));
  const scriptArrays = [];
  const arrayVals = new Map();
  // The A1 shIR is built INSIDE the transpile call — the wasm's
  // sh→A1→estree pipeline is one in-process run, so the A1 never needs
  // to cross the boundary for the sh→js path. A separate shir() call
  // would re-parse + re-run the A2/A3 analyses (var_types, lengths,
  // const, lifetimes, … — all for the C/zig/go backends, none consumed
  // by estree) + JSON-round-trip the A1, purely to extract the literal
  // arrays. The estree already carries them: provably-static arrays
  // arrive as native `let a = […]` declarators, the rest as top-level
  // `sh2.setArray("a", […])` calls. Collect both — the same shape the
  // A1 path picked (a bare-name array whose elements are all string
  // literals; a non-literal element bails, exactly like a1LiteralValue).
  const arrayLiteral = (arr) => {
    if (!arr || arr.type !== "ArrayExpression") return null;
    const vals = [];
    for (const el of arr.elements || []) {
      if (el && el.type === "Literal" && typeof el.value === "string") vals.push(String(el.value));
      else return null;
    }
    return vals;
  };
  for (const st of program.body || []) {
    const e = st && st.type === "ExpressionStatement" ? st.expression : null;
    if (e && e.type === "CallExpression" && e.callee && e.callee.type === "MemberExpression" &&
        e.callee.object && e.callee.object.type === "Identifier" && e.callee.object.name === "sh2" &&
        e.callee.property && e.callee.property.type === "Identifier" && e.callee.property.name === "setArray" &&
        e.arguments && e.arguments[0] && e.arguments[0].type === "Literal") {
      const vals = arrayLiteral(e.arguments[1]);
      if (vals) { scriptArrays.push(String(e.arguments[0].value)); arrayVals.set(String(e.arguments[0].value), vals); }
    }
    if (st && st.type === "VariableDeclaration" && st.declarations) {
      for (const d of st.declarations) {
        if (d.id && d.id.type === "Identifier") {
          const vals = arrayLiteral(d.init);
          if (vals) { scriptArrays.push(d.id.name); arrayVals.set(d.id.name, vals); }
        }
      }
    }
  }
  keepVariables(program, scriptArrays, { repl: false });
  const js =
    "// ── Generated by bash2js (otranspilerl A1 path) ──────────────\n" +
    "// bash → A1 → ESTree → JS against the sh2.* runtime — the unified\n" +
    "// wasm with the landed perf transforms (native tests, inlining, …)\n" +
    "// bash source:\n" +
    escapeJsComment(bashSource) + "\n" +
    "// ── transpiled statements ─────────────────────────────\n" +
    await estreeToJs(program, { repl: false });
  return { js, ast: program, arrayVals };
}

// ─── bashToJS: the one-call entry point ─────────────────────────
// Returns { js, ast, arrayVals? }: the generated JavaScript (header +
// transpiled statements) and the ESTree AST. Default pipeline: bash →
// ESTree (debashcl.wasm, the unified debashc CLI reactor) → JS
// (estree.js), run against the sh2.* runtime. When
// USE_OTRANSPILERL_BASH is on, the A1 path is preferred with a
// throw-fallback to debashcl.
export async function bashToJS(fs, bashSource) {
  if (USE_OTRANSPILERL_BASH) {
    try {
      return await bashToJSA1(fs, bashSource);
    } catch (e) {
      console.warn("bash2js: otranspilerl A1 path failed (" + e.message + ") — falling back to debashcl");
    }
  }
  const lib = await getSh2Lib();
  const ast = await lib.toEstree(bashSource);
  const js =
    "// ── Generated by bash2js (debashcl ESTree path) ──────────────\n" +
    "// bash → ESTree → JS against the sh2.* runtime — full bash support\n" +
    "// bash source:\n" +
    escapeJsComment(bashSource) + "\n" +
    "// ── transpiled statements ─────────────────────────────\n" +
    await estreeToJs(ast);
  return { js, ast };
}

// ─── sh2lib facade: handed to .js commands as the `sh2lib` param ─
// Lets /bin/sh2js.js, /bin/sh2perl.js, /bin/otranspiler.js (and any user
// command) drive the debashc reactor directly, in both shells — and, via
// the unified otranspilerl library (the real debashl core + all nine
// backend renderers), the full sh → A1 → target pipeline.
export function buildSh2LibFacade(fs) {
  return {
    // the shell's transpile core is otranspilerl now — toPerl/toEstree
    // use the unified wasm's in-process renderers (debashcl is only the
    // bashToJS throw-fallback + the legacy lex below).
    toPerl: (src) => getOtranspilerl().then((l) => l.transpile(String(src), "sh", "perl")),
    toEstree: (src) => getOtranspilerl().then((l) => l.transpile(String(src), "sh", "js")),
    lex: (src) => getOtranspilerl().then((l) => l.lex(String(src))),
    version: () => getOtranspilerl().then((l) => l.version()),
    bashToJs: async (src) => (await bashToJS(fs, src)).js,
    // Windows batch → JS: the bat2js pipeline (busybox's bat-sh-go
    // frontend → A1 shIR → otranspilerl estree → JS against sh2.*).
    batToJs: async (src) => (await import("./bat2js.js")).batToJS(fs, src).then((r) => r.js),
    // the unified otranspilerl library (src/otranspilerl.js):
    //   shir(src) → A1 shIR JSON       (the debashl core, full bash)
    //   transpile(src, s, t) → target  (sh/shir sources, in-process)
    //   render(a1, t) → target         (A1 → any of the nine backends)
    //   estreeToJs(estree) → JS source (the shell's own emitter)
    shir: async (src) => (await getOtranspilerl()).shir(String(src)),
    transpile: async (src, s, t) => (await getOtranspilerl()).transpile(String(src), s, t),
    render: async (a1, t) => (await getOtranspilerl()).render(String(a1), t),
    glsl: async (src) => (await getOtranspilerl()).glsl(String(src)),   // shell → GLSL ES 1.00 (the sh2glsl path)
    estreeToJs: async (estree) => estreeToJs(estree),
    // the unified frontend (src/busybox.js) — the SAME artifact the
    // otranspiler GUI uses: the shipped prebuilt
    // www/wasm-bin/otranspiler-busybox.wasm, staged into the VFS and
    // run by GoRunner (built with the in-browser Go toolchain only if
    // the prebuilt is ever missing). busyboxA1(src, lang) → A1 shIR
    // JSON for go/py/c/pl/zsh/fish sources.
    busyboxA1: async (src, lang) => {
      const { ensureBusyboxWasm, busyboxA1 } = await import("./busybox.js");
      const { GoRunner } = await import("./go.js");
      const goRunner = new GoRunner(fs, { baseUrl: "www/" });  // www/ in node CLI (page-relative in the browser)
      const fetchBytes = async () => {
        if (typeof process !== "undefined" && process.versions && process.versions.node) {
          const { readFile } = await import("node:fs/promises");
          return new Uint8Array(await readFile(process.cwd() + "/www/wasm-bin/otranspiler-busybox.wasm"));
        }
        const { BUSYBOX_VERSION } = await import("./busybox.js");
        const resp = await fetch("wasm-bin/otranspiler-busybox.wasm?v=" + BUSYBOX_VERSION);
        if (!resp.ok) throw new Error("prebuilt busybox fetch " + resp.status);
        return new Uint8Array(await resp.arrayBuffer());
      };
      const wasmPath = await ensureBusyboxWasm(fs, {
        goRunner, fetchBytes, onLog: (m) => console.log(m),
      });
      return busyboxA1(String(src), lang, { fs, wasmPath, goRunner });
    },
  };
}

// ─── runBash: transpile AND execute in one call ────────────────
// The "type bash, get generated JS executed" entry point: transpiles
// the source with bashToJS and runs the generated JS in a shell
// context where `fs`, `env`, `stdout`, `stderr` and `__runCmd` (the
// shell's own command runner — used for pipelines, redirection and
// command substitution) are in scope. Returns the script's exit code.
//
// The generated JS runs with the `sh2.*` runtime (createSh2Runtime)
// in scope. `scriptArgs` become $1..$9/$@/$#.
export async function runBash(fs, source, { stdout, stderr, runCmd, args = [], argv0 = "bash", markers = [], stdin } = {}) {
  let { js, arrayVals } = await bashToJS(fs, source);
  // Marker echos (the REPL's `echo '<marker>'` line brackets) are
  // rewritten to direct stdout writes. Running them through exec would
  // set $? to 0 right before the user's line runs — breaking
  // `false` followed by `echo $?` (real bash reports 1). A direct
  // write bypasses exec entirely, so the exit status carries across
  // the boundary exactly like in bash.
  for (const m of markers) {
    if (!m) continue;
    const write = `stdout.write(${JSON.stringify(m + "\n")})`;
    const out = JSON.stringify(m + "\n");
    // echo forms the emitters produce: the async exec dispatch, the
    // sync builtin, and the native process.stdout.write lowering (the
    // last writes to the real stdout — route it through the passed
    // stdout object like the exec form). The native statement carries
    // `, sh2.lastExit = 0[, true]` bookkeeping that would clobber $? —
    // the whole marker statement is replaced by the bare write so the
    // exit status survives the boundary like in real bash.
    // full statement forms FIRST — the bare process.stdout.write is a
    // substring of them, and the `, sh2.lastExit = 0` tail must go too.
    const forms = [
      `sh2.exec("echo", [${JSON.stringify(m)}])`,
      `sh2.builtin("echo", [${JSON.stringify(m)}])`,
      `(process.stdout.write(${out}), sh2.lastExit = 0, true)`,
      `(process.stdout.write(${out}), sh2.lastExit = 0)`,
      `process.stdout.write(${out})`,
    ];
    for (const f of forms) {
      if (js.includes(f)) { js = js.replace(f, write); break; }
    }
  }
  return runTranspiled(fs, js, { args, argv0, stdout, stderr, runCmd, arrayVals, stdin });
}

// ─── runTranspiled: run PRE-TRANSPILED generated JS with the full
// shell plumbing — the same eval/source-aware shellExec, runtime, proc
// shim and invocation runBash uses. Shared by runBash (after its
// bashToJS + marker rewrite) and the bgworker (which reuses its
// per-script transpile cache instead of re-transpiling). Without the
// eval-aware shellExec the sound generators' indirect arg parsing
// (`eval "pa_a=\${$pa_i}"` in parse_sound_args) silently no-ops and
// the generator emits its default (WAV) output instead of the --tsv.
export async function runTranspiled(fs, js, { args = [], argv0 = "bash", stdout, stderr, runCmd, arrayVals, stdin } = {}) {
  const out = stdout || { write: () => {} };
  const err = stderr || { write: (s) => out.write(s) };
  const { createSh2Runtime } = await import("./sh2runtime.js");
  // `eval "line"` / `. lib.sh` / `source lib.sh` INSIDE the transpiled
  // program run in THIS runtime's store — the shell's own source/eval
  // builtins execute on the persistent otRt (a different store), so the
  // script's variables/functions would be invisible to them (and theirs
  // to the script). bash semantics: source/eval execute in the CURRENT
  // shell. Transpile the snippet and eval it against rt.sh2 (the same
  // sh2/process the program uses), so function definitions (the sound
  // lib's sin16/sound_main) and assignments land in the shared store.
  let rt;
  // `eval "line"` snippets: the estree emits a top-level assignment as
  // `let X = ""; X = V;` — the `let` is eval-scope-local, but bash
  // eval SHARES variables (parse_sound_args's `eval "pa_a=\${$pa_i}"`
  // must set the caller's pa_a). Rewrite the scalar declare + its
  // re-assignment to store writes. SOURCED files are NOT rewritten
  // (their functions rely on the native lets).
  const evalToStore = (code) => {
    const names = [];
    let out = code.replace(/^let ([A-Za-z_][A-Za-z0-9_]*)( *= *[^;\n]*)?;/gm, (m, n, rhs) => {
      names.push(n);
      return "sh2.vars." + n + (rhs ? rhs : " = \"\"") + ";";
    });
    for (const n of names) {
      out = out.replace(new RegExp("^" + n + " =", "gm"), "sh2.vars." + n + " =");
    }
    return out;
  };
  const runInRuntime = async (src2, asEval) => {
    const { js: subJs, arrayVals } = await bashToJS(fs, src2);
    if (arrayVals) { for (const [n, v] of arrayVals) { try { rt.sh2.setArray(n, v); } catch {} } }
    const finalJs = asEval ? evalToStore(subJs) : subJs;
    const fn = new Function("args", "fs", "env", "stdout", "stderr", "__runCmd", "sh2", "process", `return (async () => { ${finalJs} })();`);
    await fn([], fs, env, out, err, shellExec, rt.sh2, proc);
  };
  const shellExec = async (cmdline, stdin2, modeType) => {
    const c = String(cmdline || "").trim();
    let m = /^(?:source|\.)\s+(\S+)(?:\s+([\s\S]*))?$/.exec(c);
    if (m) {
      const file = m[1].replace(/^['"]|['"]$/g, "");
      try {
        const content = await fs.read(file);
        if (content !== null && content !== undefined) {
          await runInRuntime(String(content));
          return { out: "", err: "", code: 0 };
        }
      } catch {}
      return { out: "", err: `source: ${file}: no such file` + "\n", code: 1 };
    }
    m = /^eval\s+([\s\S]+)$/.exec(c);
    if (m) {
      const code = m[1].replace(/^['"]|['"]$/g, "");
      try {
        await runInRuntime(code, true);
        return { out: "", err: "", code: 0 };
      } catch (e) {
        return { out: "", err: String(e && e.message ? e.message : e) + "\n", code: 2 };
      }
    }
    return runCmd ? runCmd(cmdline, stdin2, modeType) : { out: "", err: "", code: 0 };
  };
  rt = createSh2Runtime({ fs, env, shellExec, stdout: out, stderr: err, args, argv0 });
  // the otranspilerl A1 path pre-seeds the literal arrays (the A1
  // renderer drops bare `arr=(…)` reads); the debashcl path emits
  // setArray itself.
  if (arrayVals) { for (const [name, vals] of arrayVals) { try { rt.sh2.setArray(name, vals); } catch {} } }
  // pipe input → the transpiled code's read_line/getline bridge (the c
  // frontend's sh2.stdin cursor)
  if (stdin !== undefined) { try { rt.sh2.stdin = stdin; } catch {} }
  // The generated JS (the native estree backend) writes echo/error
  // output and implements `exit N` through `process` — the shared
  // runShellScript path passes its shim; runBash must too, or a script
  // crashes in the browser, where there is no node `process` at all
  // (the go.js shim, when present, is env-less and stdout-less). The
  // shim is used EVERYWHERE (Node included): it routes output through
  // the passed stdout/stderr — so the shell's capture/redirect/pipe
  // machinery sees .sh output — and `exit N` becomes the thrown
  // __otranspiler_exit__ code instead of killing the host.
  const proc = {
    stdout: out,
    stderr: err,
    pid: 1,
    argv: [argv0, ...args],
    env: env || {},
    cwd: () => (fs.cwd !== undefined ? fs.cwd : "/"),
    chdir(p) {
      if (fs && fs.cwd !== undefined) {
        fs.cwd = String(p).replace(/\/+$/, "") || "/";
        try { env.PWD = fs.cwd; } catch {}
      }
    },
    exit(code) { const e = new Error("__otranspiler_exit__" + code); e.exitCode = Number(code) || 0; throw e; },
  };
  const fn = new Function("args", "fs", "env", "stdout", "stderr", "__runCmd", "sh2", "process", `
    return (async () => {
      ${js}
    })();
  `);
  let code;
  try {
    code = await fn([], fs, env, out, err, shellExec, rt.sh2, proc);
  } catch (e) {
    if (e && e.exitCode !== undefined) return e.exitCode;  // `exit N`
    throw e;
  }
  return typeof code === "number" ? code : 0;
}
