// ─── bat2js: Windows batch (.bat) → JavaScript, transpiled in the browser ─
//
// The full batch → JS pipeline runs entirely in the browser:
//
//   .bat ──busybox (bat-sh-go)──▶ A1 shIR ──otranspilerl──▶ ESTree ──estree.js──▶ JavaScript
//
// busybox (src/busybox.js) is the merged Go frontend wasm: the bat-sh-go
// frontend — a real Windows batch lexer/parser (vendored in
// www/bin/bat-sh-go/, source gmatht/sh2loop/frontends/bat-sh-go) —
// parses the .bat source and emits the neutral A1 shIR JSON contract.
// otranspilerl (src/otranspilerl.js) is the unified transpiler library
// (the debashl core + all nine backend renderers); its estree backend
// renders the A1 → ESTree JSON, and src/estree.js lowers that to
// JavaScript against the sh2.* runtime (src/sh2runtime.js).
//
// Usage from the shell (jtsh builtin `cmd.exe`):
//   cmd.exe 'echo hello world'     → transpile + execute inline batch
//   cmd.exe /c 'echo hi'           → same (real cmd's /c)
//   cmd.exe -f script.bat          → execute a batch file from the VFS
//   cat script.bat | cmd.exe       → execute from a pipe
//   cmd.exe --js 'echo hi'         → print the generated JS (bat2js mode)
//   cmd.exe                        → interactive REPL (state persists)
// -----------------------------------------------------------------

import { env } from "./env.js";
import { getOtranspilerl } from "./otranspilerl.js";
import { estreeToJs } from "./estree.js";

function escapeJsComment(text) {
  return text.split("\n").map((l) => "//   " + l).join("\n");
}

// `set NAME=value` seed lines for the shell's environment (see runBat).
// Values carrying batch-special characters (& statement separator, %
// expansion, ^ line-continuation/escape, " quoting, ! and a trailing \
// would misparse the seed line — those are skipped (their reads stay
// empty rather than corrupt the program). The real env vars (HOME,
// PATH, USER, PWD, …) are all safe.
function seedBatchEnv(envObj) {
  const lines = [];
  for (const k of Object.keys(envObj || {})) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(k)) continue;
    const v = envObj[k];
    if (v === undefined || v === null) continue;
    const s = String(Array.isArray(v) ? v.join(" ") : v);
    if (!s || /[&%^"!]/.test(s) || /\\$/.test(s) || s.includes("\n")) continue;
    lines.push(`set ${k}=${s}`);
  }
  return lines.join("\n");
}

// ─── getBatFrontend: stage/load the merged frontend wasm ───────
// The SAME artifact the otranspiler command and GUI use: the shipped
// prebuilt www/wasm-bin/otranspiler-busybox.wasm (the merged Go binary
// with ALL frontends incl. bat-sh-go), staged into the VFS by
// src/busybox.js — built with the in-browser Go toolchain only if the
// prebuilt is ever missing. Returns { wasmPath, goRunner, busyboxA1 }.
// The GoRunner + wasm are CACHED across calls (the REPL transpiles
// every line — re-instantiating go.wasm per line would make each one
// seconds slow); the runner resets its capture state per run.
let batFrontendPromise = null;
export function getBatFrontend(fs) {
  batFrontendPromise ??= (async () => {
    const { ensureBusyboxWasm, busyboxA1 } = await import("./busybox.js");
    const { GoRunner } = await import("./go.js");
    const goRunner = new GoRunner(fs, { baseUrl: "www/" });
    const fetchBytes = async () => {
      if (typeof process !== "undefined" && process.versions && process.versions.node) {
        const { readFile } = await import("node:fs/promises");
        return new Uint8Array(
          await readFile(new URL("../www/wasm-bin/otranspiler-busybox.wasm", import.meta.url))
        );
      }
      const { BUSYBOX_VERSION } = await import("./busybox.js");
      const resp = await fetch("wasm-bin/otranspiler-busybox.wasm?v=" + BUSYBOX_VERSION);
      if (!resp.ok) throw new Error("busybox fetch " + resp.status);
      return new Uint8Array(await resp.arrayBuffer());
    };
    const wasmPath = await ensureBusyboxWasm(fs, { goRunner, fetchBytes });
    return { wasmPath, goRunner, busyboxA1 };
  })();
  return batFrontendPromise;
}

// ─── batToJS: the one-call entry point ─────────────────────────
// Returns { js, a1 }: the generated JavaScript (header + transpiled
// statements) and the A1 shIR contract. Pipeline: .bat → A1 shIR
// (busybox's bat-sh-go frontend) → ESTree (otranspilerl) → JS
// (estree.js), run against the sh2.* runtime.
export async function batToJS(fs, batSource) {
  const { wasmPath, goRunner, busyboxA1 } = await getBatFrontend(fs);
  const a1 = await busyboxA1(String(batSource), "bat", { fs, wasmPath, goRunner });
  const lib = await getOtranspilerl();
  const program = JSON.parse(lib.render(JSON.stringify(a1), "js"));
  const js =
    "// ── Generated by bat2js (busybox bat-sh-go → A1 → estree) ──────\n" +
    "// batch → A1 shIR → ESTree → JS against the sh2.* runtime\n" +
    "// batch source:\n" +
    escapeJsComment(String(batSource)) + "\n" +
    "// ── transpiled statements ─────────────────────────────\n" +
    await estreeToJs(program);
  return { js, a1 };
}

// ─── runBat: transpile AND execute in one call ────────────────
// The "type cmd, get generated JS executed" entry point (the cmd.exe
// builtin and its REPL): transpiles the batch source with batToJS and
// runs the generated JS in a shell context where `fs`, `env`, `stdout`,
// `stderr`, `__runCmd` (the shell's own command runner — used for
// pipelines, redirection and command substitution) and `sh2` are in
// scope. Returns the script's exit code.
//
// The generated JS runs with the `sh2.*` runtime (createSh2Runtime) in
// scope; `process` is a shim (like jtsh's otProc) so the estree's
// `process.stdout.write` echoes and `process.exit(N)` (batch `exit /b
// N`) behave — `exit /b N` throws a sentinel that is caught here and
// returned as the exit code, it never kills the shell. `scriptArgs`
// become %1..%9/%*/%0 (batch positionals).
//
// BATCH READS THE SHELL'S ENVIRONMENT: `%HOME%` must print the shell's
// $HOME. The otranspilerl core folds reads of never-written vars to ""
// at compile time (SH2_ASSUME_NO_ENV — the same fold jtsh's bash
// fallback defeats by seeding known vars), so the known env vars are
// seeded as `set NAME=value` declarations up front: the reads then
// compile live, and a script's own `set NAME=…` still overrides, like
// real cmd (seed first, script after).
export async function runBat(fs, source, { stdout, stderr, runCmd, args = [], argv0 = "cmd.exe" } = {}) {
  const seeded = (seedBatchEnv(env) + "\n" + source).replace(/^\n+/, "");
  const { js } = await batToJS(fs, seeded);
  const out = stdout || { write: () => {} };
  const err = stderr || { write: (s) => out.write(s) };
  const { createSh2Runtime } = await import("./sh2runtime.js");
  const rt = createSh2Runtime({ fs, env, shellExec: runCmd, stdout: out, stderr: err, args, argv0 });
  const proc = {
    stdout: out,
    stderr: err,
    pid: 1,
    argv: [argv0 || "cmd.exe"],
    env: env || {},
    cwd: () => (fs.cwd !== undefined ? fs.cwd : "/"),
    chdir(p) {
      if (fs && fs.cwd !== undefined) {
        fs.cwd = String(p).replace(/\/+$/, "") || "/";
        try { env.PWD = fs.cwd; } catch {}
      }
    },
    exit(code) {
      const e = new Error("__bat_exit__" + code);
      e.exitCode = Number(code) || 0;
      throw e;
    },
  };
  const fn = new Function("args", "fs", "env", "process", "stdout", "stderr", "__runCmd", "sh2", `
    return (async () => {
      ${js}
    })();
  `);
  try {
    const code = await fn([], fs, env, proc, out, err, runCmd, rt.sh2);
    return typeof code === "number" ? code : 0;
  } catch (e) {
    if (e && e.exitCode !== undefined) return e.exitCode;  // `exit /b N`
    throw e;
  }
}
